= RFQ API  

== APIs Summary 


The set of Tradefeedr RFQ APIs allow you to query all RFQ history provided by its liquidity providers or platforms. 
The API is split into `outrights` and `swaps`.

Refer to xref:analytics_rfs.adoc[RFQ Analytics] page for field definitions.

The set of RFQ API endpoints:

1. xref:api_rfq/api_rfq_outrights_execution_history.adoc[Outrights Execution History - v1/fx/rfq-outrights/execution-history]
** This endpoint is used query all trading events for outrights RFQ. It should be used when you require a detailed analysis and understanding of the execution
2. xref:api_rfq/api_rfq_swaps_execution_history.adoc[Swaps Execution History - v1/fx/rfq-swaps/execution-history]
** This endpoint is used query all trading events for swaps RFQ. It should be used when you require a detailed analysis and understanding of the execution
3. xref:api_rfq/api_rfq_outrights_execution_stats.adoc[Outrights Execution Stats - v1/fx/rfq-outrights/execution-stats]
** This endpoint is designed to study general execution quality of the outrights RFQ trades
4. xref:api_rfq/api_rfq_swaps_execution_stats.adoc[Swaps Execution Stats - v1/fx/rfq-swaps/execution-stats]
** This endpoint is designed to study general execution quality of the swaps RFQ trades
5. xref:api_rfq/api_rfq_outrights_opportunity_report.adoc[Outrights Opportunity Report - v1/fx/rfq-outrights/opportunity-report]
** This endpoint generates an opportunity report which displays the `OutCome` of the outrights RFQ if it was `WON` or `Lost`
6. xref:api_rfq/api_rfq_swaps_opportunity_report.adoc[Swaps Opportunity Report - v1/fx/rfq-swaps/opportunity-report]
** This endpoint generates an opportunity report which displays the `OutCome` of the swaps RFQ if it was `WON` or `Lost`
7. xref:api_rfq/api_rfq_outrights_participation_report.adoc[Outrights Participation Report - v1/fx/rfq-outrights/participation-report]
** This endpoint returns a table which summarises the outrights RFQ participation rate by `LP`
8. xref:api_rfq/api_rfq_swaps_participation_report.adoc[Swaps Participation Report - v1/fx/rfq-swaps/participation-report]
** This endpoint returns a table which summarises the swaps RFQ participation rate by `LP`