= Overview


Welcome to the documentation site for the Tradefeedr Platform and APIs.

== Tradefeedr Role

The goal of Tradefeedr is to provide clients with easy access to their trading data.

Tradefeedr’s functionally rich data APIs allows you to build analysis and workflows that fit your needs.
Tradefeedr provides optimised API calls that allow you to "slice and dice" data and extract specific views for visualisation in Data Science Notebooks or download the data for use in internal systems for further analysis.



== Getting Started

The xref:getting_started.adoc[Getting Started] tutorial provides you a quick start guide on how to run the Tradefeedr APIs. It contains information on API structure, the endpoint (can be seen as a function) and how to run a custom query.

Note that the structure of the JSON query is dependent upon the API endpoint and what parameters it can handle.

This page contains simple examples of the APIs and it is broken down into the following groups:

* Algo API
* RFS API
* Bilateral RFS API
* RFQ API


The Python code used to generate the result is presented with each example. It can be copied and run directly on the platform to generate the same results.


== User Guide

The xref:user_guide.adoc[User Guide] contains an overview of the different user guides found on this site.

This page is used to help navigate you to the documentation you seek.

==  Analytics

The xref:analytics.adoc[Analytics] pages contains information on the various metrics, providing you an comprehensive understanding of the APIs.
Thus, enabling you to carry out your analysis using the Tradefeedr endpoints. Furthermore, we have included
thorough description of the Tradefeedr models that are being used.

Also, refer to the xref:user_guide.adoc[User Guide] for analytics guides.

== API

The xref:api.adoc[API] page provides you a remote access guide, running the APIs away from the Tradefeedr Platform.
Also, a breakdown of API structure and it's components.

For API endpoint guides refer to the xref:user_guide.adoc[User Guide].

== Platform User Guide

This guide explains how the Tradefeedr platform works and all the various layers it contains.

It is useful to understand how the API, widget and template report notebooks are constructed.
As it would provide you the ability customise/modify the notebooks to their own needs.

* xref:platform.adoc[Platform Guide]
